version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studyawslambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pqav88funvof"
s3_prefix = "studyawslambda"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
